### GENERAL SETTINGS ###

# Site settings
title: Spree Forty Three
description: "Apps that pop!"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.spreefortythree.com/"
include: [".well-known"]

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#cddc39" #"#F70031"
  primary_rgb: "205,220,57" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#56764e" #"#33004D"
  link: "#cddc39"
  link_hover: "#56764e"
  footer_heading: "#ffffff"
  footer_content: "#cddc39"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: "https://www.facebook.com/spreefortythree"
  - title: twitter
    url: "https://twitter.com/spreefortythree"
  - title: instagram
    url: "https://www.instagram.com/spreefortythree/"

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Kirchdorfer Str. 8
    - 10318 Berlin
    - Germany
email: support@spreefortythree.com
#tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Laura Sommers
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We started developing aviation apps in 2015. Now we are working on all kinds of apps that we are passionate about, for Windows, iOS and Android. All from the wonderful city of Berlin."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "The best aviation weather app in the Windows Store. And also great developer support. It's really worth for a small fee."
    author: Jan
    position: USER REVIEW - MICROSOFT STORE
